<?php

/**
 * @file
 * Contains metatag_fine_grained_perms.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\metatag\Plugin\Field\FieldWidget\MetatagFirehose;

/**
 * Implements hook_field_widget_form_alter().
 */
function metatag_fine_grained_perms_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['widget'] instanceof MetatagFirehose) {
    foreach (Element::children($element) as $group_id) {
      // By default restrict access to group and regain access when user has
      // access to at least one tag in group to prevent displaying empty groups.
      $element[$group_id]['#access'] = FALSE;

      foreach (Element::children($element[$group_id]) as $tag_id) {
        // Check tag permission.
        $element[$group_id][$tag_id]['#access'] = \Drupal::currentUser()
          ->hasPermission('access metatag tag ' . $group_id . '__' . $tag_id);

        // Make group accessible if user has access to tag.
        if ($element[$group_id][$tag_id]['#access']) {
          $element[$group_id]['#access'] = TRUE;
        }
      }
    }
  }
}
