<?php

/**
 * @file
 * Replace the default multi-select boxes with two panels list and filter.
 */

/**
 * Implements hook_page_attachments().
 */
function improved_multi_select_page_attachments(&$attachments) {
  $activated = FALSE;
  $config = \Drupal::config('improved_multi_select.settings');
  $context = [
    'url'          => trim($config->get('url')),
    'request_path' => \Drupal::request()->getRequestUri(),
    'selectors'    => array_filter(explode("\n", str_replace("\r", "\n", trim($config->get('selectors'))))),
  ];

  // Activated on replace all option.
  if ($replace_all = $config->get('isall')) {
    $activated = TRUE;
  }
  // Activated based on the matching path or not empty selectors in the module settings.
  elseif (($context['url'] && \Drupal::service('path.matcher')->matchPath($context['request_path'], $context['url'])) || $context['selectors']) {
    $activated = TRUE;
  }

  // Allow other modules to activate or deactivate our module for specific pages.
  \Drupal::moduleHandler()->alter('improved_multi_select_activated', $activated, $context);
  if (!$activated) {
    return;
  }

  $drupal_settings = [
    'selectors'           => improved_multi_select_load_selectors($replace_all, $context['selectors']),
    'filtertype'          => $config->get('filtertype'),
    'orderable'           => $config->get('orderable'),
    'groupresetfilter'    => $config->get('groupresetfilter'),
    'buttontext_add'      => $config->get('buttontext_add'),
    'buttontext_addall'   => $config->get('buttontext_addall'),
    'buttontext_del'      => $config->get('buttontext_del'),
    'buttontext_delall'   => $config->get('buttontext_delall'),
    'buttontext_moveup'   => $config->get('buttontext_moveup'),
    'buttontext_movedown' => $config->get('buttontext_movedown'),
  ];

  // Allow other modules to alter our data.
  \Drupal::moduleHandler()->alter('improved_multi_select_attached', $drupal_settings, $context);

  $attachments['#attached']['library'][] = 'improved_multi_select/ims';
  $attachments['#attached']['drupalSettings']['improved_multi_select'] = $drupal_settings;
}

/**
 * Return array of jQuery selectors from jQuery selectors or 'replace all' option.
 *
 * @param boolean $replace_all
 *   Boolean indicating if all multiselects will be replaced.
 * @param array $selectors
 *   Array with jQuery selectors.
 *
 * @return array
 *   Array with jQuery selectors.
 */
function improved_multi_select_load_selectors($replace_all, $selectors) {
  $output = [];
  if (!empty($selectors) and !$replace_all) {
    foreach ($selectors as $selector) {
      $output[] = $selector;
    }
  }
  else {
    $output = ['select[multiple]'];
  }
  return $output;
}
