definitions:
  contact__site_page:
    weight: -50
    menu_name: footer
    parent: ''
    enabled: false
    expanded: false
  standard__front_page:
    weight: -46
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  system__admin_content:
    weight: -62
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_structure:
    weight: -61
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -60
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -59
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -58
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -57
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -56
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: -54
    enabled: false
    menu_name: admin
    parent: system.admin
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
